import React from 'react'

const RandomText = () => {
  return (
    <div className="randomText">
        <p>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Hic magnam sunt labore dicta, cumque officia eius consequatur impedit facilis distinctio, nemo repellat minus, iusto inventore deleniti iste nam fugit rem eaque ea earum perspiciatis! Dolorem cumque accusamus saepe magni tempore tenetur soluta cupiditate nulla voluptas doloribus repellendus molestiae exercitationem voluptatem dicta aliquid, expedita nisi eius, perferendis, amet nesciunt eum ea quo. Incidunt impedit soluta modi esse perspiciatis saepe? Necessitatibus quasi adipisci autem beatae dignissimos perspiciatis sit quo recusandae dicta, ex in ab cum minus molestias voluptate, ipsum nihil vero saepe ratione. Et tenetur hic explicabo aperiam eius nesciunt minus molestias dolorum laudantium consequuntur porro harum impedit quam odit quos ducimus fugit vitae sint consectetur accusamus. Exercitationem perferendis, amet, labore nesciunt nisi, illum impedit numquam expedita perspiciatis ducimus harum pariatur quibusdam modi vitae reiciendis adipisci libero nam blanditiis magni explicabo itaque maxime voluptate ea odio? Accusantium suscipit nisi quibusdam dignissimos! Doloremque veniam suscipit quod! Nisi sint cupiditate voluptates aut totam esse id nemo sed, fuga, ex iste, ipsum voluptatem placeat. Incidunt repellendus, beatae commodi aspernatur officia error accusamus reiciendis! Eius expedita aliquid consequatur placeat perspiciatis error voluptate! Dolore voluptate distinctio ab reprehenderit maiores repellendus, id rem ut iste sapiente explicabo sint? Lorem ipsum dolor sit amet consectetur adipisicing elit. Hic molestiae obcaecati corporis possimus adipisci debitis voluptas pariatur impedit. Quo temporibus maxime modi porro non, voluptate eveniet tempore, debitis aliquid quae ad iusto sequi neque dignissimos eaque sed aspernatur aut, quas optio distinctio incidunt numquam. Asperiores voluptate, tenetur impedit ratione perspiciatis eos et ducimus sint quod aliquam esse hic laudantium natus aspernatur accusantium? Excepturi, nobis aliquam? Amet, voluptate voluptas quidem omnis illo ipsum? Placeat repudiandae minima iure pariatur, ducimus maxime voluptates magni porro sapiente aliquid obcaecati modi assumenda nam blanditiis neque non incidunt fugit velit quia earum aspernatur itaque. Ipsum, exercitationem.</p>
    </div>
  )
}

export default RandomText